# Generated by Django 3.1.2 on 2020-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='result_csv',
            field=models.FileField(editable=False, upload_to=''),
        ),
    ]
