# Generated by Django 3.1.2 on 2020-10-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0002_auto_20201013_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('Processing', 'Processing'), ('Done', 'Done')], max_length=60, null=True)),
                ('network', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=60, null=True)),
            ],
        ),
    ]
