# Generated by Django 3.1.2 on 2020-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0002_auto_20201025_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Processing', 'Processing'), ('Done', 'Done')], default='Idle', editable=False, max_length=60),
        ),
    ]
