# Generated by Django 3.1.2 on 2020-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0003_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
