# Generated by Django 3.1.2 on 2020-10-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0004_csvfile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='date_uploaded',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='csv',
            field=models.FileField(null=True, upload_to='CSVs/%Y/%m/%d/'),
        ),
    ]
