# Generated by Django 3.1.2 on 2020-10-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0004_auto_20201025_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='result_csv',
            field=models.FileField(default='', editable=False, null=True, upload_to=''),
        ),
    ]
