# Generated by Django 3.1.2 on 2020-10-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvmanager', '0005_auto_20201013_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csvmanager.user'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
